midas:
  kafka:
    transactions-topic: transactions

general:
  kafka-topic: transactions 

spring:
  kafka:
    consumer:
      group-id: midas-core-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"   # allow deserialization of all packages
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver

# Optional if you are running tests that use JPA
jpa:
  hibernate:
    ddl-auto: create-drop
  show-sql: true
